### PR TITLE
Status code 412 indicates condition not met — ne need for regex

### PR DESCRIPTION
**Pull request by jonmv**
@vekterli please reivew.

### CODE REVIEW

**Review by vekterli — APPROVED** [review]
:+1: out of curiosity, what are we returning now as part of the response body?

**Comment by jonmv** [comment]
`"pathId": ...` and `"message": <thing from backend>`, like:
`[UNKNOWN(251013) @ tcp/vespa5.factory.corp.gq1.yahoo.com:19112/default]: ReturnCode(TEST_AND_SET_CONDITION_FAILED, Document does not exist partition=0, nodeIndex=0 bucket=20bcd79478b1e483 ) `

**Comment by jonmv** [comment]
Could prepend a more humanised error message if you think that's valuable.

**Comment by vekterli** [comment]
Looks good the way it is 🦄

**Comment by jonmv** [comment]
Unicorn

**Pull request merged**
