### PR TITLE
Add baseline performance tests for feeding to mixed tensors.

### PR DESCRIPTION
**Pull request by geirst**
@arnej27959 please review
@havardpe FYI

### CODE REVIEW

**Review by arnej27959 — APPROVED** [review]
👍

**Review by havardpe — APPROVED** [review]
we probably need to benchmark with both number and string labels (after small numbers become direct string ids not backed by the shared store).

**Comment by geirst** [comment]
Yes, I can extend the tests with that in the next iteration.

**Comment by geirst** [comment]
Using both number and string labels is added here: https://github.com/vespa-engine/system-test/pull/1246

**Pull request merged**
