### PR TITLE
Use reconfigurable dispatcher on factory

### PR DESCRIPTION
**Pull request by jonmv**
@bjorncs please review, but do not merge.

### CODE REVIEW

**Comment by jonmv** [comment]
Want some runs without this, with the modified code merged, first.

**Comment by jonmv** [comment]
Also requires https://github.com/vespa-engine/vespa/pull/27774

**Review by bjorncs — APPROVED** [review]

**Comment by aressem** [comment]
Missing a comma

**Comment by jonmv** [comment]
:'(

**Pull request merged**
