### PR TITLE
Use attribute, not index, for numeric fields

### PR DESCRIPTION
**Pull request by hmusum**
Please review only

### CODE REVIEW

**Comment by bratseth** [comment]
We should keep "attribute | index" in a few tests though?

**Comment by baldersheim** [comment]
In one test where we also check that a warning is given.

**Comment by hmusum** [comment]
There are 2 tests that keep "attribute | index", but it makes sense to add a test with this and check for warninrg, I'll look into it

**Comment by hmusum** [comment]
@baldersheim please have a look again

**Review by baldersheim — APPROVED** [review]

**Pull request merged**
