### PR TITLE
Account for clock skew on factory in reindexing test

### PR DESCRIPTION
**Pull request by jonmv**
@hmusum

### CODE REVIEW

**Review by hmusum — APPROVED** [review]
OK, but if we have clock skew on test nodes all sorts of strange things might happen and I'd rather fix that instead.

**Comment by jonmv** [comment]
What amount of skew can we accept? This test runs a clock sensitive query immediately after feeding documents, so only a very small amount of skew will make it fail.

**Comment by jonmv** [comment]
But, yes, we should have control over the clock skew. @aressem what's the status on this?

**Comment by jonmv** [comment]
The test has been failing more than others — if this fixes that, it was skew.

**Pull request merged**
