### PR TITLE
Bjorncs/tls preps 

### PR DESCRIPTION
**Pull request by bjorncs**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by bjorncs** [comment]
I did not write that description myself...

**Comment by vekterli** [comment]
Looks like the CLA bot is off wandering in the woods. Probably why you got the legalese text when creating the PR.

**Comment by bjorncs** [comment]
Merging manually since the CLA checker is stuck

**Comment by hmusum** [comment]
Build fails with:

Error: test_search(TestbaseTest): NoMethodError: undefined method `https_client' for nil:NilClass
00:03:17 /sd/workspace/src/git.ouroath.com/vespa/systemtests/system-test/lib/nodetypes/vespa_node.rb:21:in `initialize'

might be related this PR.

**Comment by bjorncs** [comment]
Where do you see that error?

**Comment by hmusum** [comment]
In the build of our internal systemtests repo

**Pull request merged**
